analyzer:
  exclude:
    - lib/**/**.config.dart
    - lib/**/**.g.dart
    - lib/**/**.freezed.dart
    - lib/generated/**
    - test/**
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    prefer_constructors_over_static_methods: false
    sort_pub_dependencies: false
  # Dart
  
    

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
